server:
 servlet:
  context-path: /ELibrary

spring:
 messages:
  basename: messages
 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8
  cache: false

 datasource:
  url: jdbc:h2:mem:userDB
  driver-class-name: org.h2.Driver
  username: sa
  password: sa

 h2:
  console:
   enabled: true
   path: /h2-console

 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    format_sql: true



